### ISSUE TITLE
ktfmt fails on a trailing comma for a list of lambdas

### ISSUE THREAD

**Issue by TrevorStoneEpic** [facebook/ktfmt#203]
Similar to #47 and #59 

ktfmt fails to run on this valid code

```kotlin
listOf<() -> Unit>(
   {
        println("test")
    },
   {
        println("test")
    },
)
```

```
error: expected token: ','; generated ) instead

com.google.googlejavaformat.FormattingError: 36:25: error: expected token: ','; generated ) instead

	at com.google.googlejavaformat.OpsBuilder.token(OpsBuilder.java:315)
	at com.facebook.ktfmt.KotlinInputAstVisitorBase.token(KotlinInputAstVisitorBase.kt:2242)
```

**Comment by cgrushko** [comment]
The following snippet works for me:
```
fun f() {
    val a =
        listOf<() -> Unit>(
            { println("test") },
            { println("test") },
        )
}
```

Can you find a minimal repro? you can use the online formatter at https://facebookincubator.github.io/ktfmt/ .

**Comment by TrevorStoneEpic** [comment]
Sorry, you're right, but if you delete the second item in the list it breaks, so just

```kotlin
fun f() {
    val a =
        listOf<() -> Unit>(
            { println("test") },
        )
}
```

**Comment by hick209** [comment]
I tested on 0.44 and this is working fine.
Closing, but feel free to reopen if it is still an issue
