### ISSUE TITLE
java.lang.Throwable: Stub index points to a file 

### ISSUE THREAD

**Issue by danny-su** [facebook/ktfmt#367]
IntelliJ 2022.3

java.lang.Throwable: Stub index points to a file (file = jar:///Users/danny/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.21/1a2eaf898a0dda83037034b10a42053cf8a7caf8/kotlin-stdlib-1.7.21.jar!/kotlin/Unit.class, file type = com.intellij.ide.highlighter.JavaClassFileType@1395c6d4, indexed file type = com.intellij.ide.highlighter.JavaClassFileType@1395c6d4) without indexed stub tree; indexing stamp = indexing timestamp = 1669607461711, binary = true, byte size = 757, char size = -1, can have stubs = true, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:41)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:198)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:197)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:103)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:91)
	at org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex.get(KotlinFullClassNameIndex.kt:17)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findClassOrObjectDeclarations$1.invoke(IDEKotlinAsJavaSupport.kt:50)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findClassOrObjectDeclarations$1.invoke(IDEKotlinAsJavaSupport.kt:49)
	at org.jetbrains.kotlin.idea.base.util.DumbModeUtils.runReadActionInSmartMode(DumbModeUtils.kt:17)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.findClassOrObjectDeclarations(IDEKotlinAsJavaSupport.kt:49)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClassesAndObjects(JavaElementFinder.kt:61)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClasses(JavaElementFinder.kt:46)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClass(JavaElementFinder.kt:35)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:93)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:71)
	at org.jetbrains.kotlin.idea.base.projectStructure.KotlinProjectStructureUtils$hasKotlinJvmRuntime$1.invoke(KotlinProjectStructureUtils.kt:131)
	at org.jetbrains.kotlin.idea.base.projectStructure.KotlinProjectStructureUtils$hasKotlinJvmRuntime$1.invoke(KotlinProjectStructureUtils.kt:128)
	at org.jetbrains.kotlin.idea.base.util.DumbModeUtils.runWithAlternativeResolveEnabled$lambda-1(DumbModeUtils.kt:24)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:354)
	at org.jetbrains.kotlin.idea.base.util.DumbModeUtils.runWithAlternativeResolveEnabled(DumbModeUtils.kt:24)
	at org.jetbrains.kotlin.idea.base.projectStructure.KotlinProjectStructureUtils.hasKotlinJvmRuntime(KotlinProjectStructureUtils.kt:128)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt$hasAnyKotlinRuntimeInScope$1.invoke$lambda-0(ConfigureKotlinInProjectUtils.kt:310)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:723)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:55)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt$hasAnyKotlinRuntimeInScope$1.invoke(ConfigureKotlinInProjectUtils.kt:309)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt$hasAnyKotlinRuntimeInScope$1.invoke(ConfigureKotlinInProjectUtils.kt:307)
	at org.jetbrains.kotlin.idea.core.KotlinPluginDisposableUtils.syncNonBlockingReadAction$lambda-0(KotlinPluginDisposable.kt:29)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:464)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:218)
	at org.jetbrains.kotlin.idea.core.KotlinPluginDisposableUtils.syncNonBlockingReadAction(KotlinPluginDisposable.kt:31)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt.hasAnyKotlinRuntimeInScope(ConfigureKotlinInProjectUtils.kt:307)
	at org.jetbrains.kotlin.idea.gradleCodeInsightCommon.KotlinWithGradleConfigurator.getStatus(KotlinWithGradleConfigurator.kt:51)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt.isModuleConfigured(ConfigureKotlinInProjectUtils.kt:111)
	at org.jetbrains.kotlin.idea.configuration.ConfigureKotlinInProjectUtilsKt.isNotConfiguredNotificationRequired(ConfigureKotlinInProjectUtils.kt:197)
	at org.jetbrains.kotlin.idea.configuration.KotlinSetupEnvironmentNotificationProvider.collectNotificationData(KotlinSetupEnvironmentNotificationProvider.kt:63)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$componentProvider$1.invoke(EditorNotificationsImpl.kt:205)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$componentProvider$1.invoke(EditorNotificationsImpl.kt:203)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:90)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:73)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:125)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda-1$lambda-0(cancellableReadAction.kt:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda-1(cancellableReadAction.kt:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:59)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:54)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:54)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:46)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invokeSuspend(InternalReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$2.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:23)
	at com.intellij.openapi.application.rw.PlatformReadActionSupport.executeReadAction(PlatformReadActionSupport.kt:24)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:51)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:19)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:203)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by cgrushko** [comment]
I don't see anything related to ktfmt here...
