### ISSUE TITLE
KFMT_idea_plugin crashes with Intellij 2024.3

### ISSUE THREAD

**Issue by olivierbeltrandocintoo** [facebook/ktfmt#523]
Hello, the ktfmt_idea_plugin crashes with version 2024.3 of Intellij.

Steps to reproduce:
* Install the plugin
* format code with `ctrl` + `alt` + `l`

System:
* Windows 11

Here is the stacktrace: 
```
java.lang.ExceptionInInitializerError
	at com.facebook.ktfmt.format.Formatter.sortedAndDistinctImports(Formatter.kt:157)
	at com.facebook.ktfmt.format.Formatter.format(Formatter.kt:103)
	at com.facebook.ktfmt.intellij.KtfmtFormattingService$KtfmtFormattingTask.run(KtfmtFormattingService.kt:62)
	at com.intellij.formatting.service.AsyncDocumentFormattingService$FormattingRequestImpl.runTask(AsyncDocumentFormattingService.java:261)
	at com.intellij.formatting.service.AsyncDocumentFormattingService.runAsyncFormat(AsyncDocumentFormattingService.java:106)
	at com.intellij.formatting.service.AsyncDocumentFormattingService$FormattingProgressTask.run(AsyncDocumentFormattingService.java:380)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsupportedOperationException
	at java.base/sun.nio.fs.WindowsFileSystem.close(WindowsFileSystem.java:91)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.close(DelegatingFileSystem.java:40)
	at org.jetbrains.kotlin.com.intellij.ide.plugins.DescriptorLoadingContext.close(DescriptorLoadingContext.java:49)
	at org.jetbrains.kotlin.com.intellij.ide.plugins.PluginManagerCore.registerExtensionPointAndExtensions(PluginManagerCore.java:1327)
	at org.jetbrains.kotlin.com.intellij.core.CoreApplicationEnvironment.registerExtensionPointAndExtensions(CoreApplicationEnvironment.java:287)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationExtensionPointsAndExtensionsFrom(KotlinCoreEnvironment.kt:625)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:595)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironment(KotlinCoreEnvironment.kt:505)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironmentForProduction(KotlinCoreEnvironment.kt:492)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:440)
	at com.facebook.ktfmt.format.Parser.<clinit>(Parser.kt:57)
	... 36 more
```

![image](https://github.com/user-attachments/assets/e78c006c-e232-4ac8-a5c4-953863355115)

Thanks in advance :)
Cheers,
Olivier

**Comment by WeisSebastian** [comment]
Having the same issue with the same stack traces. Can confirm it started happening after upgrading to IntelliJ 2024.3

**Comment by jessestricker** [comment]
This also happens in the latest IntelliJ IDEA 2024.3.1 patch release.

**Comment by levifernandesfs** [comment]
Did you resolve this issue?

**Comment by hick209** [comment]
What version of the plugin are you using?
Do you have K2 mode enabled in your IDE?
What is your IDE version?

I have not yet been able to reproduce it with either K1 nor K2 modes
IDE version: IC-243.21565.193
ktfmt plugin version: 1.2.0.53

**Comment by hick209** [comment]
Oh, I'm on macOS, could that be it? 🤔
If so I might need help on this one since I don't have a Windows machine

**Comment by olivierbeltrandocintoo** [comment]
Version of Intellij: 
- IntelliJ IDEA 2024.3.1.1 (Community Edition)
- Build #IC-243.22562.218, built on December 18, 2024

![image](https://github.com/user-attachments/assets/4284130b-1d8d-4ecb-bb1b-207ab62255f0)

Version of the ktfmt plugin: `1.2.0.53`
![image](https://github.com/user-attachments/assets/13a7b482-6ce1-44b5-9f77-e35f6b0357b8)

K2 is enabled
![image](https://github.com/user-attachments/assets/f106c37b-6f26-4b09-86b4-576b1451ac2a)

Thanks a lot in advance for the help :)

**Comment by JavierSegoviaCordoba** [comment]
> Oh, I'm on macOS, could that be it? 🤔
> 
> If so I might need help on this one since I don't have a Windows machine

It only happens on Windows.

**Comment by janchristian-haddorp** [comment]
Just as info if not clear so far... Setting of K2 mode flag doesn't matter - same issue independent of K2 mode setting.

In our team we are using IntelliJ IDEA Ultimate (2024.3.1.1 / #IU-243.22562.218), all on Windows. Happy to support.

**Comment by c1rcle** [comment]
`ktfmt` is targeting Kotlin 1.8.22 whose compiler depends on an ancient IntelliJ platform SDK (203.8084.24). I bumped Kotlin to the latest stable version (2.1.0), built the plugin locally and it seems to work just fine. Not sure whether this is an acceptable solution though.

**Comment by hick209** [comment]
@c1rcle that's a great finding! How about 2.0.0 would that work? If so I can make another release with that

**Comment by c1rcle** [comment]
@hick209 Just ran a quick test and yeah, 2.0.0 works too. Verified on IntelliJ IDEA 2024.3.1.1 (243.22562.218).

**Comment by hick209** [comment]
Awesome! Bumping it to 2.0.0 then. Let's hope this fixes things

**Comment by olivierbeltrandocintoo** [comment]
Then probably consider using 2.0.X (like 2.0.10 or 2.0.20) that contain bugfixes found in 2.0.0 :) 
But maybe this is not relevant. Thanks for everything

**Comment by hick209** [comment]
[Released 0.54](https://github.com/facebook/ktfmt/releases/tag/v0.54) that hopefully will fix this issue.

For now we're on 2.0.0, but we are discussing pushing to the latest 2.0.x, which would be 2.0.21, as that would be quite similar to 2.0.0 except for some code fixes.

Right now we only bumped to 2.0.0 to try to make sure ktfmt is available for a broad range of use cases.

**Comment by olivierbeltrandocintoo** [comment]
Excellent news, I have been hitting the refresh button this morning a lot of times in Intellij, but no luck yet, the version 0.54 of the plugin does not appear in the marketplace (yet)

![Image](https://github.com/user-attachments/assets/de142398-7276-4807-abda-5e1eeb0242bb)
https://plugins.jetbrains.com/plugin/14912-ktfmt/versions

How long does it take to normally show up ?

**Comment by ezamelczyk** [comment]
Normally I'd just install the plugin manually from the releases page but I see that you do not distribute installable plugin package there. Is there a reason for that?

**Comment by hick209** [comment]
@olivierbeltrandocintoo, it's probably stuck in JB review process, which can take a while. According to Google up to 4 days, but usually it's a couple of days from what I've seem with ktfmt

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/f75f07fc-75ab-425e-a788-dee2b2ccbf0e" />


@ezamelczyk, that's actually a good idea for now, it's just extra work. Do you happen to know or have pointers on how we could automate that? If we do this, it would be guaranteed to be there all the time

**Comment by olivierbeltrandocintoo** [comment]
It's there !
![Image](https://github.com/user-attachments/assets/310f7623-ff7d-423b-b2c6-6c23bd9d2747)

Also available inside Intellij from the marketplace !

And it works 🍾 🤩 

Really awesome !! Thanks a lot to all 😄

**Comment by hick209** [comment]
That's awesome!
Thanks everyone for reporting, for your help towards finding a fix and for the patience while we get it out there

**Comment by ezamelczyk** [comment]
@hick209 sorry I've never built an IntellijIDEA plugin so I'm not sure how to do that but isn't the package you're uploading to the jetbrains marketplace basically the same thing? It should be just a zip file afaik.
